### ISSUE TITLE
缺失接口： `getMVUrl`

### ISSUE THREAD

**Issue by a632079** [XGHeaven/netease-music-sdk#1]
浏览 Docs， 未发现该接口的实现

**Comment by XGHeaven** [comment]
抱歉，现在才看到。我晚上回去看一下😂

**Comment by XGHeaven** [comment]
已添加了

**Comment by vc1** [comment]
@XGHeaven  之前我自己也写了一个，时间一长没空弄了，有的接口参数是前端改js，抓包得出来的，比网上的全，代码怎么发给你？

**Comment by XGHeaven** [comment]
这个如果可以的话，你可以给 NeteaseCloudApi 也贡献一下，如果少的话直接贴到这里就好了。多的话给一个 gist 也行 @vc1

**Comment by vc1** [comment]
@XGHeaven 
按功能改过文件结构，npm test跑不通了，不过源码很清楚，可以参考下

[music.zip](https://github.com/XGHeaven/netease-music-sdk/files/2117726/music.zip)
